# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Pierre Felgines
paginate:       10
baseurl:        ""
url:            "https://felginep.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Pierre Felgines
  url:          http://github.com/felginep
  email:        ""

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/chesterhow/tale

# Gems
plugins:
  - jekyll-paginate
